### ISSUE TITLE
TS3 Plugin API version 21 not supported?

### ISSUE THREAD

**Issue by DSDV** [thorwe/CrossTalk#40] opened 2017-01-15 09:19 UTC
Hello Guys,
since latest updates to the Teamspeak Client the addon is disabled due to the fact that it dindt support the newest version of the addon API? 

is there a workaround or fix for that problem?

with best +DS_DV+

PS: sorry for my bad english

**Comment by Bluscream** [comment] 2017-01-15 16:28
Duplicate of #36

**Comment by DSDV** [comment] 2017-01-15 17:28
sorry

**Comment by Bluscream** [comment] 2017-01-15 18:38
Please close your issue and comment on the original one instead :)

**Closed** 2017-09-17 13:40 UTC
